---
- name: OCP ClusterLogging and ClusterLogForwarding
  hosts: bastion
  tasks:
  - name: Include the global-secret-update role
    include_role:
        name: global-secret-update
    when: 
      - clusterlogging_clf_cs != "" and loki_clf_cs != ""
      - clusterlogging_clf_cs != None and loki_clf_cs != None
      - clf_clean_up == false

  - name: Include the ClusterLogging and ClusterLogForwarding role
    include_role:
        name: ocp-cluster-logging
    when: clf_clean_up == false
  
  - name: Clean up cluster logging 
    include_tasks: "{{ playbook_dir }}/roles/ocp-cluster-logging/files/clf-cleanup.yml"
    when: clf_clean_up 

